# Site settings
title: Melnikov's layer

email: melnikovdv@gmail.com

description: > # this means to ignore newlines until "baseurl:"
  This is page of Dmitriy Melnikov, software developer from Saint-Petersburg, Russia. 
  Here you can find interesting topics about development, gadgets, Android, Scala and other stuff.

author: 
  name: Dmitriy Melnikov

baseurl: "" # the subpath of your site, e.g. /blog/

url: "http://melnikovdv.github.io" # the base hostname & protocol for your site

# Build settings
markdown: kramdown
